apiVersion: v1
kind: Service
metadata:
  name: mongodb-external-0
  namespace: informationgrid
spec:
  selector:
    statefulset.kubernetes.io/pod-name: mongodb-0
  ports:
    - port: 27017
      nodePort: 27017
  type: NodePort
