apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mongo-db
  namespace: informationgrid
spec:
  releaseName: mongodb
  chart:
    spec:
      chart: mongodb
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      version: 10.28.7
  interval: 10m
  install:
    remediation:
      retries: 3
  values:
    architecture: replicaset
    arbiter:
      enabled: false
    replicaCount: 1
    auth: 
      enabled: false
    externalAccess:
      enabled: false
      service:
        type: NodePort
        nodePorts:
          - 27017