apiVersion: v1
kind: Service
metadata:
  name: informationgrid
  namespace: informationgrid
spec:
  selector:
    app: minikube-informationgrid
  ports:
    - port: 8080
      name: web
      nodePort: 8081
    - port: 9090
      name: admin
      nodePort: 9091     
    - port: 11311
      name: telnet
      nodePort: 11311        
  type: NodePort
