apiVersion: kubernetes.crossplane.io/v1alpha1
kind: Object
metadata:
  name: k3s-workload-ns
spec:
  forProvider:
    manifest:
      apiVersion: v1
      kind: Namespace
      metadata:
        # name in manifest is optional and defaults to Object name
        # name: some-other-name
        labels:
          example: "true"
  providerConfigRef:
    name: k3s-provider